---
# tasks file for Puppet

- hosts: agent
  become: yes
  become_user: root

  tasks:
    - name: Verify the repository path is exists or not.
      stat: path=/tmp/puppetlabs-release-el-{{ ansible_distribution_major_version }}.noarch.rpm
      register: repository

    - name: Download the Puppetlabs repository from their public repo.
      get_url: url=https://yum.puppetlabs.com/puppetlabs-release-el-{{ ansible_distribution_major_version }}.noarch.rpm dest=/tmp/

    - name: Install Puppet repository.
      yum: name=/tmp/puppetlabs-release-el-{{ ansible_distribution_major_version }}.noarch.rpm state=present

    - name: Install Puppet agent
      yum: name=puppet state=installed
